aspnet-core/src/TownSend.Web.Mvc/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Abp.Application.Services.Dto;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using TownSend.Authorization.Users;
using TownSend.BlobUtilitys;
using TownSend.Common.Dto;
using TownSend.Controllers;
using TownSend.Documents;
using TownSend.Documents.Dto;
using TownSend.Identity;
using TownSend.Partners.Dto;
using TownSend.Payments;
using TownSend.ProfileNotes;
using TownSend.ProfileNotes.Dto;
using TownSend.Web.Models;

namespace TownSend.Web.Controllers
{
    public class CommonController : TownSendControllerBase
    {
        private IProfileNoteAppService _profileNoteAppService;
        private UserManager _userManager;
        private IDocumentAppService _documentAppService;
        private readonly SignInManager _signInManager;
        private readonly IPaymentAppService _paymentAppService;
            
        public CommonController(
                                IProfileNoteAppService profileNoteAppService,
                                UserManager userManager,
                                IDocumentAppService documentAppService,
                                SignInManager signInManager,
                                IPaymentAppService paymentAppService
                                )
        {
            _profileNoteAppService = profileNoteAppService;
            _userManager = userManager;
            _documentAppService = documentAppService;
            _signInManager = signInManager;
            _paymentAppService = paymentAppService;
        }        

        
        public async Task<IActionResult> TestCreateCustomerAccount()
        {
            _paymentAppService.CreateCustomerInQuickbooks();
            return View();
        }

        public async Task<IActionResult> CreateProfileNote(CreateProfileNoteDto input)
        {
            
            await _profileNoteAppService.CreateProfileNote(input);
            if(input.Type==EntityType.Partners)
            {
                TempData["Type"] = Constant.Success;
                TempData["Message"] = Constant.noteAdded;
                TempData["partnertab"] = "Notes";
                return RedirectToAction("EditPartner", new RouteValueDictionary(
                new { controller = "Partners", action = "EditPartner", Id = input.MapId }));                
            }
            else if(input.Type==EntityType.Teams)
            {
                TempData["Type"] = Constant.Success;
                TempData["Message"] = Constant.noteAdded;
                TempData["teamtab"] = "Notes";
                return RedirectToAction("EditTeam", new RouteValueDictionary(
               new { controller = "Teams", action = "EditTeam", Id = input.MapId }));
            }
            else if(input.Type==EntityType.Members)
            {
                TempData["Type"] = Constant.Success;
                TempData["Message"] = Constant.noteAdded;
                TempData["membertab"] = "Notes";
                return RedirectToAction("EditMember", new RouteValueDictionary(new { controller = "Members", action = "EditMember", Id = input.MapId }));
            }
            
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> UpdateDocument(DocumentDto input)
        {
            if (input.Restrict == null)
            {
                input.VisibleDateFrom = null;
                input.VisibleDateTo = null;
            }
            else
            {
                IFormatProvider culture = new CultureInfo("en-US", true);
                input.VisibleDateFrom = DateTime.ParseExact(input.StringVisibleDateFrom, "MM-dd-yyyy", culture);
                input.VisibleDateTo = DateTime.ParseExact(input.StringVisibleDateTo, "MM-dd-yyyy", culture);
            }

            await _documentAppService.UpdateDocumentAsync(input);
            TempData["Type"] = Constant.Success;
            TempData["Message"] = Constant.documentUpdate;
            if (EntityType.Partners == input.Type)
            {
                TempData["partnertab"] = "Documents";
                return RedirectToAction("EditPartner", new RouteValueDictionary(new { controller = "Partners", action = "EditPartner", Id = input.MapId }));
            }
            else if (EntityType.Teams == input.Type)
            {
                TempData["teamtab"] = "Documents";
                return RedirectToAction("EditTeam", new RouteValueDictionary(new { controller = "Teams", action = "EditTeam", Id = input.MapId }));
            }
            else if(EntityType.Members==input.Type)
            {
                TempData["membertab"] = "Documents";
                return RedirectToAction("EditMember", new RouteValueDictionary(new { controller = "Members", action = "EditMember", Id = input.MapId }));
            }
        
            return View("Index", "Error");
        }
        [HttpPost]
        public async Task<IActionResult> DeleteDocument([FromBody]DocumentDeleteDto documentDeleteDto)
        {
            
            EntityType entityType = (EntityType)Enum.Parse(typeof(EntityType), documentDeleteDto.entityType);  // Animal.Dog
            await _documentAppService.DeleteDocumentAsync(documentDeleteDto.DocumentId,entityType);
            if (EntityType.Partners== entityType)
            {
                TempData["partnertab"] = "Documents";
            }
            if (EntityType.Teams == entityType)
            {
                TempData["teamtab"] = "Documents";
            }
            if(EntityType.Members==entityType)
            {
                TempData["membertab"] = "Documents";
            }
            TempData["Type"] = Constant.Success;
            TempData["Message"] = Constant.documentRemoved;
            return Json(true);
        }
        public async Task<IActionResult> DownLoadDocument(int id,EntityType type,int mapId)
        { 
            //CheckPermission();
            var data = await _documentAppService.GetDocumentForEditAsync(id);
            if (data == null)
                return View("~/Views/Shared/ErrorMessage.cshtml", new ErrorMessageModel() { Message = "Requested document did not found", AlertType = "warning" });



            string filePath = data.DocumentPath;
            string fileName = data.Name;



            var fileExist = BlobUtility.FileInBlob(filePath, "tlgdocuments", fileName);



            if (fileExist.Result)
            {
                var fileResult = BlobUtility.StreamFromBlob(filePath, "tlgdocuments", fileName);
                var file = fileResult.Result;
                file.Stream.Position = 0;
                Thread.Sleep(1000);
                HttpContext.Response.Headers.Add("Set-Cookie", "fileDownload=true; path =/");
                HttpContext.Response.Headers.Add("Cache-Control", "no-cache, no-store, must-revalidate");
                return File(file.Stream, file.ContentType, file.FileName);
            }



            return View("~/Views/Shared/ErrorMessage.cshtml", new ErrorMessageModel() { Message = "Requested document did not found", AlertType = "warning" });
        }
        //[HttpPost]
        public async Task<JsonResult> CheckEmail(string Email)
        {
            var users = await _userManager.FindByEmailAsync(Email);
           
            if (users == null)
            {
                return Json(true);
            }
            else
            {
                return Json(false);
            }

        }

    }
}

aspnet-core/src/TownSend.Web.Mvc/Views/Shared/Components/AccountLanguages/AccountLanguagesViewComponent.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Abp.Localization;

namespace TownSend.Web.Views.Shared.Components.AccountLanguages
{
    public class AccountLanguagesViewComponent : TownSendViewComponent
    {
        private readonly ILanguageManager _languageManager;

        public AccountLanguagesViewComponent(ILanguageManager languageManager)
        {
            _languageManager = languageManager;
        }

        public Task<IViewComponentResult> InvokeAsync()
        {
            var model = new LanguageSelectionViewModel
            {
                CurrentLanguage = _languageManager.CurrentLanguage,
                Languages = _languageManager.GetLanguages().Where(l => !l.IsDisabled).ToList()
                .Where(l => !l.IsDisabled)
                .ToList(),
                CurrentUrl = Request.Path
            };

            return Task.FromResult(View(model) as IViewComponentResult);
        }
    }
}

aspnet-core/src/TownSend.Web.Mvc/Views/Shared/Components/Document/DocumentViewComponent.cs
using Abp.Application.Services.Dto;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TownSend.Common.Dto;
using TownSend.Documents;
using TownSend.Documents.Dto;
using TownSend.Partners;
using TownSend.Partners.Dto;
using TownSend.Web.Models.Partners;

namespace TownSend.Web.Views.Shared.Components.Document
{
    public class DocumentViewComponent : TownSendViewComponent
    {
        private readonly IDocumentAppService _documentAppService;
        public DocumentViewComponent(IDocumentAppService documentAppService)
        {
            _documentAppService = documentAppService;
        }
        public async Task<IViewComponentResult> InvokeAsync(int id,EntityType type)
        {
            var etype = new EntityTypeMapDto() {MapId=id,Type=type };
            var documents = await _documentAppService.GetDocuments(etype);
            var viewmodel = new DocumentViewModel();
            viewmodel.Documents = documents.Items;
            viewmodel.Type = etype.Type;
            viewmodel.MapId = id;
            //var documents = await _partnerAppService.GetDocumentsAsync(new GetDocumentInput() { PartnerId = Id });
            //var viewmodel = new DocumentViewModel
            //{
            //    //PartnerId = model.Partner.Id,
            //    Documents = documents.Items
            //};

            return View(viewmodel);
        }
    }
}

aspnet-core/src/TownSend.Web.Mvc/Views/Shared/Components/ProfileNote/ProfileNoteViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TownSend.Common.Dto;
using TownSend.Partners;
using TownSend.ProfileNotes;
using TownSend.ProfileNotes.Dto;

namespace TownSend.Web.Views.Shared.Components.ProfileNote
{
    public class ProfileNoteViewComponent : TownSendViewComponent
    {
        private readonly IProfileNoteAppService _profileNoteAppService;

        public ProfileNoteViewComponent(IProfileNoteAppService profileNoteAppService)
        {
            _profileNoteAppService = profileNoteAppService;
        }
        public async Task<IViewComponentResult> InvokeAsync(int id, EntityType type)
        {
            var etype = new EntityTypeMapDto() { MapId = id, Type = type };
            var notes = await _profileNoteAppService.GetNotes(etype);
          
            var viewModel = new ProfileNoteViewModel() {ProfileNotes=notes.Items,Type=etype.Type,MapId=id };
            return View(viewModel);
        }
    }
}

aspnet-core/src/TownSend.Web.Mvc/Views/Shared/Components/RecommendedLinks/RecommendedLinksViewComponent.cs
using Abp.Application.Services.Dto;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TownSend.Partners;

namespace TownSend.Web.Views.Shared.Components.RecommendedLink
{
    public class RecommendedLinksViewComponent : TownSendViewComponent
    {
        private IPartnerAppService _partnerAppService;

        public RecommendedLinksViewComponent(IPartnerAppService  partnerAppService)
        {
            _partnerAppService = partnerAppService;
        }        

        public async Task<IViewComponentResult> InvokeAsync(int Id)
        {
            var model = new RecommendedLinksViewModel
            {
                GetRecommendedLinksOutput = await _partnerAppService.GetRecommendedLinksByPartnerId(new EntityDto(Id))
            };


            return View(model);

        }




    }
}

aspnet-core/src/TownSend.Web.Mvc/Views/Shared/Components/RightSideBar/RightSideBarViewComponent.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Abp.Configuration;
using TownSend.Configuration;
using TownSend.Configuration.Ui;

namespace TownSend.Web.Views.Shared.Components.RightSideBar
{
    public class RightSideBarViewComponent : TownSendViewComponent
    {
        private readonly ISettingManager _settingManager;

        public RightSideBarViewComponent(ISettingManager settingManager)
        {
            _settingManager = settingManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var themeName = await _settingManager.GetSettingValueAsync(AppSettingNames.UiTheme);

            var viewModel = new RightSideBarViewModel
            {
                CurrentTheme = UiThemes.All.FirstOrDefault(t => t.CssClass == themeName)
            };

            return View(viewModel);
        }
    }
}

aspnet-core/src/TownSend.Web.Mvc/Views/Shared/Components/SideBarNav/SideBarNavViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Abp.Application.Navigation;
using Abp.Runtime.Session;

namespace TownSend.Web.Views.Shared.Components.SideBarNav
{
    public class SideBarNavViewComponent : TownSendViewComponent
    {
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly IAbpSession _abpSession;

        public SideBarNavViewComponent(
            IUserNavigationManager userNavigationManager,
            IAbpSession abpSession)
        {
            _userNavigationManager = userNavigationManager;
            _abpSession = abpSession;
        }

        public async Task<IViewComponentResult> InvokeAsync(string activeMenu = "")
        {
            var model = new SideBarNavViewModel
            {
                MainMenu = await _userNavigationManager.GetMenuAsync("MainMenu", _abpSession.ToUserIdentifier()),
                ActiveMenuItemName = activeMenu
            };

            return View(model);
        }
    }
}

aspnet-core/src/TownSend.Web.Mvc/Views/Shared/Components/SideBarUserArea/SideBarUserAreaViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Abp.Configuration.Startup;
using TownSend.Sessions;

namespace TownSend.Web.Views.Shared.Components.SideBarUserArea
{
    public class SideBarUserAreaViewComponent : TownSendViewComponent
    {
        private readonly ISessionAppService _sessionAppService;
        private readonly IMultiTenancyConfig _multiTenancyConfig;

        public SideBarUserAreaViewComponent(ISessionAppService sessionAppService,
            IMultiTenancyConfig multiTenancyConfig)
        {
            _sessionAppService = sessionAppService;
            _multiTenancyConfig = multiTenancyConfig;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = new SideBarUserAreaViewModel
            {
                LoginInformations = await _sessionAppService.GetCurrentLoginInformations(),
                IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled,
            };

            return View(model);
        }
    }
}

aspnet-core/src/TownSend.Web.Mvc/Views/Shared/Components/TenantChange/TenantChangeViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Abp.AutoMapper;
using Abp.ObjectMapping;
using TownSend.Sessions;

namespace TownSend.Web.Views.Shared.Components.TenantChange
{
    public class TenantChangeViewComponent : TownSendViewComponent
    {
        private readonly ISessionAppService _sessionAppService;
        private readonly IObjectMapper _objectMapper;

        public TenantChangeViewComponent(ISessionAppService sessionAppService, 
            IObjectMapper objectMapper)
        {
            _sessionAppService = sessionAppService;
            _objectMapper = objectMapper;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var loginInfo = await _sessionAppService.GetCurrentLoginInformations();
            var model = _objectMapper.Map<TenantChangeViewModel>(loginInfo);
            return View(model);
        }
    }
}

aspnet-core/src/TownSend.Web.Mvc/Views/Shared/Components/TopBarLanguageSwitch/TopBarLanguageSwitchViewComponent.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Abp.Localization;

namespace TownSend.Web.Views.Shared.Components.TopBarLanguageSwitch
{
    public class TopBarLanguageSwitchViewComponent : TownSendViewComponent
    {
        private readonly ILanguageManager _languageManager;

        public TopBarLanguageSwitchViewComponent(ILanguageManager languageManager)
        {
            _languageManager = languageManager;
        }

        public IViewComponentResult Invoke()
        {
            var model = new TopBarLanguageSwitchViewModel
            {
                CurrentLanguage = _languageManager.CurrentLanguage,
                Languages = _languageManager.GetLanguages().Where(l => !l.IsDisabled).ToList()
            };

            return View(model);
        }
    }
}

aspnet-core/src/TownSend.Web.Mvc/Views/Shared/Components/ProfileNote/Default.cshtml
@using System.Text.Encodings.Web
@using TownSend.Web.Views.Shared.Components.ProfileNote
@model ProfileNoteViewModel
@*@if (Model.Languages.Count > 1)
    {
        <div class="language-switch-area">
            @foreach (var languageInfo in Model.Languages)
            {
                <a href="~/AbpLocalization/ChangeCulture?cultureName=@(languageInfo.Name)&returnUrl=@(UrlEncoder.Default.Encode(Context.Request.Path + Context.Request.QueryString))">
                    <span class="language-icon @(languageInfo == Model.CurrentLanguage ? "language-icon-current" : "")" title="@languageInfo.DisplayName"><i class="@languageInfo.Icon"></i></span>
                </a>
            }
        </div>
    }*@
@section Scripts{
    <script src="~/view-resources/Views/Common/ProfileNote.js"></script>

}
@{
    var noteactiveclass = "";
    if (TempData["teamtab"] != null && TempData["teamtab"].ToString() == "Notes")
    {
        noteactiveclass = "show active";
    }
    if (TempData["partnertab"] != null && TempData["partnertab"].ToString() == "Notes")
    {
        noteactiveclass = "show active";
    }
    if(TempData["membertab"]!=null && TempData["membertab"].ToString() == "Notes")
    {
         noteactiveclass = "show active";
    }


}
<div class="tab-pane @noteactiveclass" id="notesTab" role="tabpanel">

    <div class="content-container">
        <div class="card" style="border:none !important">
            <div class="row">
                <div class="col-5">
                    <h2>Note List</h2>
                </div>

                @*@if (User.IsInRole("Admin"))
                    {*@
                <div class="col-3 offset-4">
                    <a data-is-modal="true"
                       class="btn btn-secondary float-right icon-space" style="cursor: pointer;" data-toggle="modal" data-target="#NoteDefaultModal"><i class="fas fa-plus-circle"></i>ADD A NOTE</a>
                </div>
                @*}*@
            </div>
            @*<form id="SupplierNoteForm" method="post" data-ajax="true" data-ajax-url="/Partners/PartnerProfile?handler=LoadNotes&ContactID=@Model.Partner.ContactID" data-ajax-update="#SupplierNotes" data-ajax-method="get">*@
            @*<form id="SupplierNoteForm" method="post">
                    <div>

                    </div>




                </form>*@

            <div class="row padding">
                <div id="SupplierNotes" class="col-sm-12 no-padding" data-from="#SupplierNoteForm" data-is-datatable="true">
                    @if (Model.ProfileNotes != null)
                    {

                        <table class="table table-hover dataTableClass" data-paging="true" table-layout="fixed" style="width: 100%;border:1px solid rgba(0, 0, 0, 0.125)">
                            <thead class="table-header-dark" style="width:100%">
                                <tr>
                                    <th class="hidden-col no-sort" style="width: 10%;"></th>
                                    <th scope="col" style="width:50%">NOTE DESCRIPTION</th>
                                    <th scope="col" style="width:20%">ADDED BY</th>
                                    <th scope="col" style="width:20%">NOTE DATE</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var note in Model.ProfileNotes)
                                {
                                    <tr>
                                        <td class="td-first-col" style="width:2px !important">
                                            <div class="col-1 customer-photo">
                                                <i class="fas fa-comment fa-2x"></i>
                                            </div>
                                        </td>
                                        <td style="width:500px !important;margin-left:0px !important"> @note.Description</td>
                                        <td> @note.AddedBy</td>
                                        <td> @note.CreationTime.Value.ToString("MM-dd-yyyy")</td>
                                    </tr>
                                }
                            </tbody>
                        </table>

                    }
                </div>
            </div>
        </div>
    </div>
</div>

<form method="post" asp-controller="Common" asp-action="CreateProfileNote" name="add-notes" id="CreateNoteForm">
    @* changes-- *@

    <div class="modal fade" id="NoteDefaultModal" data-backdrop="static" data-update-page="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">ADD A NOTE</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-labelledby="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @*@Html.HiddenFor(model => Model.ContextLinkID)
                        @Html.HiddenFor(model => Model.UserName)*@
                    @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
                    <input type="hidden" name="MapId" value="@Model.MapId" />
                    <input type="hidden" name="Type" value="@Model.Type" />
                    <input type="hidden" />
                    <div id="validation-summary" class="text-danger" hidden="hidden">
                        <ul></ul>
                    </div>

                    <div class="row form-group">
                        <div class="col">
                            <label class="custom-form-label">Note Description</label>
                            <textarea name="Description" class="form-control description" required></textarea>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="submit" id="addnotebtn" class="btn btn-primary btn-sm">ADD<span id="spinner" style="display: none"><i class="fa fa-spinner fa-spin" aria-hidden="true"></i></span></button>
                    <button type="button" class="btn btn-dark btn-sm" data-dismiss="modal">CLOSE</button>

                </div>
            </div>
        </div>
    </div>
</form>