aspnet-core/src/TownSend.Web.Mvc/Controllers/RolesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Abp.Application.Services.Dto;
using Abp.AspNetCore.Mvc.Authorization;
using TownSend.Authorization;
using TownSend.Controllers;
using TownSend.Roles;
using TownSend.Roles.Dto;
using TownSend.Web.Models.Roles;
using Microsoft.AspNetCore.Routing;

namespace TownSend.Web.Controllers
{
    [AbpMvcAuthorize(PermissionNames.Pages_Roles)]
    public class RolesController : TownSendControllerBase
    {
        private readonly IRoleAppService _roleAppService;

        public RolesController(IRoleAppService roleAppService)
        {
            _roleAppService = roleAppService;
        }

        public async Task<IActionResult> Index()
        {
            var roles = (await _roleAppService.GetRolesAsync(new GetRolesInput())).Items;
            var permissions = (await _roleAppService.GetAllPermissions()).Items;
            var model = new RoleListViewModel
            {
                Roles = roles,
                Permissions = permissions
            };

            return View(model);
        }

        public async Task<ActionResult> EditRoleModal(int roleId)
        {
            var output = await _roleAppService.GetRoleForEdit(new EntityDto(roleId));
            var model = ObjectMapper.Map<EditRoleModalViewModel>(output);

            return View("_EditRoleModal", model);
        }

        [HttpPost]
        public async Task<ActionResult> UpdateRoleAsync(EditRoleModalViewModel input)
        {
            var roleDto = new RoleDto() { Id = input.Role.Id, Description = input.Role.Description, Name = input.Role.Name, DisplayName = input.Role.DisplayName, GrantedPermissions = input.GrantedPermissionNames };
            await _roleAppService.UpdateAsync(roleDto);
            return RedirectToAction("Index");
        }
    }
}

aspnet-core/src/TownSend.Web.Mvc/Controllers/ScholarshipController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Abp.AspNetCore.Mvc.Authorization;
using Abp.Runtime.Validation;
using Abp.UI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using TownSend.Controllers;
using TownSend.Identity;
using TownSend.Scholarships;
using TownSend.Scholarships.Dto;
using TownSend.Teams;
using TownSend.Web.Models.Scholarships;
using static TownSend.Scholarships.ScholarshipManager;

namespace TownSend.Web.Controllers
{
    [DisableValidation]
    [AbpMvcAuthorize("Pages.Scholarships")]
    public class ScholarshipController : TownSendControllerBase
    {
        #region Field
        private readonly ITeamAppService _teamAppService;
        private readonly IScholarshipAppService _scholarshipAppService;
        private readonly ScholarshipManager _scholarshipManager;
        private readonly SignInManager _signInManager;
        #endregion

        #region Ctor
        public ScholarshipController(ITeamAppService teamAppService,
                                        IScholarshipAppService scholarshipAppService,
                                        ScholarshipManager scholarshipManager,
                                        SignInManager signInManager)
        {
            _teamAppService = teamAppService;
            _scholarshipAppService = scholarshipAppService;
            _scholarshipManager = scholarshipManager;
            _signInManager = signInManager;
        }
        #endregion

        #region Methods
        /// <summary>
        /// This Method Give Scholarship Registration Page To Fill Form And Send Request
        /// Affected Entities
        /// Scholarship
        /// Member
        /// User
        /// Invite
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Register()
        {
            ScholarshipSignupViewModel model = new ScholarshipSignupViewModel();
            var teams = await _teamAppService.GetAll();
            model.TeamList = teams;            
           
            return View(model);
        }

        /// <summary>
        /// This Method is Post Method Of Register Page This Method Take Value From Member And Fill Into Scholarship Details Table
        /// Affected Table
        /// Member
        /// Scholarship
        /// Invite
        /// User
        /// ScholarshipStatus
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(ScholarshipSignupViewModel model)
        {
            try
            {
                model.TeamList = await _teamAppService.GetAll();

                if (!ModelState.IsValid)
                {
                    //return page 
                    ModelState.AddModelError(string.Empty,"Please Refresh The page");
                    return View(model);
                }

                var result = await _scholarshipAppService.CreateAsync(model.ScholarshipRegister);

                if (!result.IsSuccess)
                {
                    model.ErrorMessage = result.ErrorMessage;
                    return View(model);
                }

                TempData["Type"] = Constant.Success;
                TempData["Message"] = Constant.ScholarshipIvitationSent;
                return RedirectToAction("Register");
            }
            catch (Exception ex)
            {
                throw ex;
                //throw new UserFriendlyException(ex.Message);
            }
        }
        /// <summary>
        /// This Method Display Scholarship Details Page And Update First Page Of Scholarship Details
        /// Affected Entities
        /// Scholarship
        /// Member
        /// Scholarship Status
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [AbpMvcAuthorize("Pages.Scholarships.List")]
        public async Task<IActionResult> UpdateScholarshipInfo(ScholarshipDetailsViewModel model)
        {
            try
            {
                ModelState.Remove("ScholarshipDetails.Questionnaire.GrowthDetails");
                ModelState.Remove("ScholarshipDetails.Questionnaire.AchivementsDetails");
                ModelState.Remove("ScholarshipDetails.Questionnaire.LifeExperienceDetails");
                ModelState.Remove("ScholarshipDetails.Questionnaire.FutureGoalDetails");
                ModelState.Remove("ScholarshipDetails.Questionnaire.FirstTimeinTLP");
                ModelState.Remove("ScholarshipDetails.Questionnaire.FirstTimeApply");
                ModelState.Remove("ScholarshipDetails.ScholarshipRegister.EmailAddress");
                ModelState.Remove("ScholarshipDetails.ScholarshipRegister.FirstName");
                ModelState.Remove("ScholarshipDetails.ScholarshipRegister.LastName");
                ModelState.Remove("ScholarshipDetails.ScholarshipRegister.TeamId");

                if (ModelState.IsValid)
                {
                    ScholarshipInfoEditDto dto = new ScholarshipInfoEditDto
                    {
                        ScholarshipId = model.ScholarshipDetails.Questionnaire.ScholarshipId,
                        FirstName = model.ScholarshipDetails.MemberFirstName,
                        LastName = model.ScholarshipDetails.MemberLastName,
                        PhoneNumber = model.ScholarshipDetails.MemberPhoneNumber,
                        ScholarshipAmount = model.ScholarshipDetails.ScholarshipRegister.ScholarshipAmount
                    };

                    await _scholarshipAppService.UpdateScholarshipInfo(dto);

                    TempData["Type"] = Constant.Success;
                    TempData["Message"] = Constant.RecordsUpdatedMessage;
                }
                else
                {
                    TempData["Type"] = Constant.Error;
                    TempData["Message"] = Constant.ModelstateNotValid;
                }
            }
            catch (Exception ex)
            {
                TempData["Type"] = Constant.Error;
                TempData["Message"] = Constant.SomethingwentWrong;
            }
            TempData["scholarshiptab"] = "ScholarshipInfo";
            return RedirectToAction("ScholarshipDetail", new { model.ScholarshipDetails.Questionnaire.ScholarshipId });
        }
        /// <summary>
        /// This Method Display Scholarship Details Page And Update Second Page Of Scholarship Questionnaire
        /// Affected Entities
        /// Scholarship
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        //[AbpMvcAuthorize("Pages.Scholarships.List")]
        public async Task<IActionResult> UpdateQuestionnaire(ScholarshipDetailsViewModel model)
        {
            try
            {                
                ModelState.Remove("ScholarshipDetails.ScholarshipRegister.EmailAddress");
                ModelState.Remove("ScholarshipDetails.ScholarshipRegister.FirstName");
                ModelState.Remove("ScholarshipDetails.ScholarshipRegister.LastName");
                ModelState.Remove("ScholarshipDetails.ScholarshipRegister.TeamId");
                ModelState.Remove("ScholarshipDetails.ScholarshipRegister.ScholarshipAmount");
                ModelState.Remove("ScholarshipDetails.MemberLastName");
                ModelState.Remove("ScholarshipDetails.MemberFirstName");
                ModelState.Remove("ScholarshipDetails.Questionnaire.GrowthDetails");
                
                
                if (ModelState.IsValid)
                {
                    QuestionnaireDto dto = new QuestionnaireDto
                    {
                        ScholarshipId = model.ScholarshipDetails.Questionnaire.ScholarshipId,
                        FirstTimeApply = model.ScholarshipDetails.Questionnaire.FirstTimeApply,
                        FirstTimeinTLP = model.ScholarshipDetails.Questionnaire.FirstTimeinTLP,
                        GrowthDetails = model.ScholarshipDetails.Questionnaire.GrowthDetails,
                        AchivementsDetails = model.ScholarshipDetails.Questionnaire.AchivementsDetails,
                        LifeExperienceDetails = model.ScholarshipDetails.Questionnaire.LifeExperienceDetails,
                        FutureGoalDetails = model.ScholarshipDetails.Questionnaire.FutureGoalDetails
                    };

                    await _scholarshipAppService.UpdateQuestionnaire(dto);

                    TempData["Type"] = Constant.Success;
                    TempData["Message"] = Constant.RecordsUpdatedMessage;
                }
                else
                {
                    TempData["Type"] = Constant.Error;
                    TempData["Message"] = Constant.ModelstateNotValid;
                }
            }
            catch (Exception ex)
            {
                TempData["Type"] = Constant.Error;
                TempData["Message"] = Constant.SomethingwentWrong;
            }
            TempData["scholarshiptab"] = "ScholarshipQuestionnaireResult";
            return RedirectToAction("ScholarshipDetail", new { model.ScholarshipDetails.Questionnaire.ScholarshipId });
        }


        /// <summary>
        /// This Method Is Called On When Member is Fill Questionnaire Form Of Scholarship Invite 
        /// Affected Entities
        /// Scholarship 
        /// Member
        /// </summary>
        /// <param name="scholarshipId"></param>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Questionnaire(int scholarshipId)
        {
            //remove session

aspnet-core/src/TownSend.Web.Mvc/Views/Shared/Components/AccountLanguages/AccountLanguagesViewComponent.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Abp.Localization;

namespace TownSend.Web.Views.Shared.Components.AccountLanguages
{
    public class AccountLanguagesViewComponent : TownSendViewComponent
    {
        private readonly ILanguageManager _languageManager;

        public AccountLanguagesViewComponent(ILanguageManager languageManager)
        {
            _languageManager = languageManager;
        }

        public Task<IViewComponentResult> InvokeAsync()
        {
            var model = new LanguageSelectionViewModel
            {
                CurrentLanguage = _languageManager.CurrentLanguage,
                Languages = _languageManager.GetLanguages().Where(l => !l.IsDisabled).ToList()
                .Where(l => !l.IsDisabled)
                .ToList(),
                CurrentUrl = Request.Path
            };

            return Task.FromResult(View(model) as IViewComponentResult);
        }
    }
}

aspnet-core/src/TownSend.Web.Mvc/Views/Shared/Components/Document/DocumentViewComponent.cs
using Abp.Application.Services.Dto;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TownSend.Common.Dto;
using TownSend.Documents;
using TownSend.Documents.Dto;
using TownSend.Partners;
using TownSend.Partners.Dto;
using TownSend.Web.Models.Partners;

namespace TownSend.Web.Views.Shared.Components.Document
{
    public class DocumentViewComponent : TownSendViewComponent
    {
        private readonly IDocumentAppService _documentAppService;
        public DocumentViewComponent(IDocumentAppService documentAppService)
        {
            _documentAppService = documentAppService;
        }
        public async Task<IViewComponentResult> InvokeAsync(int id,EntityType type)
        {
            var etype = new EntityTypeMapDto() {MapId=id,Type=type };
            var documents = await _documentAppService.GetDocuments(etype);
            var viewmodel = new DocumentViewModel();
            viewmodel.Documents = documents.Items;
            viewmodel.Type = etype.Type;
            viewmodel.MapId = id;
            //var documents = await _partnerAppService.GetDocumentsAsync(new GetDocumentInput() { PartnerId = Id });
            //var viewmodel = new DocumentViewModel
            //{
            //    //PartnerId = model.Partner.Id,
            //    Documents = documents.Items
            //};

            return View(viewmodel);
        }
    }
}

aspnet-core/src/TownSend.Web.Mvc/Views/Shared/Components/ProfileNote/ProfileNoteViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TownSend.Common.Dto;
using TownSend.Partners;
using TownSend.ProfileNotes;
using TownSend.ProfileNotes.Dto;

namespace TownSend.Web.Views.Shared.Components.ProfileNote
{
    public class ProfileNoteViewComponent : TownSendViewComponent
    {
        private readonly IProfileNoteAppService _profileNoteAppService;

        public ProfileNoteViewComponent(IProfileNoteAppService profileNoteAppService)
        {
            _profileNoteAppService = profileNoteAppService;
        }
        public async Task<IViewComponentResult> InvokeAsync(int id, EntityType type)
        {
            var etype = new EntityTypeMapDto() { MapId = id, Type = type };
            var notes = await _profileNoteAppService.GetNotes(etype);
          
            var viewModel = new ProfileNoteViewModel() {ProfileNotes=notes.Items,Type=etype.Type,MapId=id };
            return View(viewModel);
        }
    }
}

aspnet-core/src/TownSend.Web.Mvc/Views/Shared/Components/RecommendedLinks/RecommendedLinksViewComponent.cs
using Abp.Application.Services.Dto;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TownSend.Partners;

namespace TownSend.Web.Views.Shared.Components.RecommendedLink
{
    public class RecommendedLinksViewComponent : TownSendViewComponent
    {
        private IPartnerAppService _partnerAppService;

        public RecommendedLinksViewComponent(IPartnerAppService  partnerAppService)
        {
            _partnerAppService = partnerAppService;
        }        

        public async Task<IViewComponentResult> InvokeAsync(int Id)
        {
            var model = new RecommendedLinksViewModel
            {
                GetRecommendedLinksOutput = await _partnerAppService.GetRecommendedLinksByPartnerId(new EntityDto(Id))
            };


            return View(model);

        }




    }
}

aspnet-core/src/TownSend.Web.Mvc/Views/Shared/Components/RightSideBar/RightSideBarViewComponent.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Abp.Configuration;
using TownSend.Configuration;
using TownSend.Configuration.Ui;

namespace TownSend.Web.Views.Shared.Components.RightSideBar
{
    public class RightSideBarViewComponent : TownSendViewComponent
    {
        private readonly ISettingManager _settingManager;

        public RightSideBarViewComponent(ISettingManager settingManager)
        {
            _settingManager = settingManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var themeName = await _settingManager.GetSettingValueAsync(AppSettingNames.UiTheme);

            var viewModel = new RightSideBarViewModel
            {
                CurrentTheme = UiThemes.All.FirstOrDefault(t => t.CssClass == themeName)
            };

            return View(viewModel);
        }
    }
}

aspnet-core/src/TownSend.Web.Mvc/Views/Shared/ErrorMessage.cshtml
@model TownSend.Web.Models.ErrorMessageModel
@{
    Layout = "~/Views/Account/_LoginLayout.cshtml";
}

<div style="margin-top: 5rem;">
    <div class="alert alert-@Model.AlertType fade show">
        @*<h4 class="alert-heading"><i class="fa @Model.Icon"></i> @Model.Heading</h4>*@
        @if (@Model.AlertType == "warning" || @Model.AlertType == "danger")
        {
            <h4>Our apologies, something has gone wrong.</h4>
        }
        else
        {
            <h4 class="alert-heading"><i class="fa @Model.Icon"></i> @Model.Heading</h4>
        }
        <hr>
        <p class="mb-0">@Html.Raw(Model.Message)</p>
    </div>
</div>

aspnet-core/src/TownSend.Web.Mvc/Views/Shared/_EditInfoButton.cshtml
    <script>       
        function toggleConfirm(button) {
            let buttons = $(button).parent().children("button");
            var form = $(button).parents('form');
            if ($(button).is(buttons.first())) {
                $(button).hide();
                $(buttons[1]).show();
                $(buttons.last()).show();
                //$(".info").find('input[type=text]:first').focus();
                $(form).find(".info").find('input[type=text]:first').focus();
            }
            else if ($(button).is(buttons.last())) {
                $(buttons[1]).hide();
                $(buttons.last()).hide();
                $(buttons.first()).show();

            }

            $(form).find(".info").prop("disabled", function (i, v) { return !v; });
            $(form).find(".dropdown-toggle").toggleClass("disabled");
            //$(".info").prop("disabled", function (i, v) { return !v; });
            //$(".dropdown-toggle").toggleClass("disabled");
        }
    </script>

<button type="button" class="btn btn-secondary float-right h-100 icon-space" style="padding-left:10px;padding-right:10px;margin-right:15px" onclick="toggleConfirm(this)" id="edit-info"><i class="fas fa-pen"></i> EDIT INFO</button>
<button type="submit" style="display: none;margin-right: 1em;" class="btn btn-success float-right h-100 EditBtn" id="EditBasicInfo"><i class='fas fa-save'></i> SAVE</button>
<button data-action-link="true" data-view-loader-refresh="#myAccountForm" type="button" style="display: none;margin-right: 1em;" class="btn btn-secondary float-right h-100" onclick="toggleConfirm(this)" id="cancel-edit-info">CANCEL</button>

aspnet-core/src/TownSend.Web.Mvc/Views/Shared/_HeaderBeforeLogin.cshtml
<header>
    <nav class="navbar fixed-top navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <a asp-controller="Home" asp-action="Index" class="navbar-brand"><img style="margin-left:10px;width:150px;height:60px" src="~/Townsend/images/mytlg-header-logo.png" /></a>
    </nav>
</header>

aspnet-core/src/TownSend.Web.Mvc/Views/Shared/_LeftNav.cshtml
@*@using TownSend.Web.Views.Shared.Components.SideBarNav
@await Component.InvokeAsync(typeof(SideBarNavViewComponent), new { activeMenu = ViewBag.CurrentPageName })*@

<nav id="my-menu">
    <ul>
        <li></li>
        @if (IsGranted("Pages.Members"))
        {
            <li><a asp-controller="" asp-action=""><strong>Members</strong></a></li>
        }
        @if (IsGranted("Pages.Partners"))
        {
            <li><a asp-controller="Partners" asp-action="Index"><strong>Partners</strong></a></li>
        }
        @if (IsGranted("Pages.Teams"))
        {
            <li id="Teams">
                <span><strong>Teams</strong></span>
                <ul>
                    <li><a asp-controller="Teams" asp-action="Index"><strong>TLP Teams</strong></a></li>
                    <li><a asp-controller="" asp-action=""><strong>Coaching</strong></a></li>
                    <li><a asp-controller="" asp-action=""><strong>Consulting</strong></a></li>
                </ul>
            </li>
        }
        @if (IsGranted("Pages.Meetings"))
        {
            <li><a asp-controller="" asp-action=""><strong>Meetings</strong></a></li>
        }
        @if (IsGranted("Pages.Dashboard"))
        {
            <li><a asp-controller="" asp-action=""><strong>Dashboard</strong></a></li>
        }
        @if (IsGranted("Pages.Reports"))
        {
            <li>
                <span><strong>Reports</strong></span>
                <ul>
                    <li><a asp-controller="" asp-action=""><strong>Payment Summary</strong></a></li>
                    <li><a asp-controller="" asp-action=""><strong>Member Payment Logs</strong></a></li>
                </ul>
            </li>
        }
        @if (IsGranted("Pages.Referrals"))
        {
            <li>
                <span><strong>Referrals</strong></span>
                <ul>
                    <li>
                        <span><strong>Referral Registration</strong></span>
                        <ul>
                            <li><a asp-controller="" asp-action=""><strong>Partner Referral</strong></a></li>
                            <li><a asp-controller="" asp-action=""><strong>TLP Teams Referral</strong></a></li>
                            <li><a asp-controller="" asp-action=""><strong>Coaching Referral</strong></a></li>
                            <li><a asp-controller="" asp-action=""><strong>Consulting Referral</strong></a></li>
                            <li><a asp-controller="" asp-action=""><strong>Essential Work</strong></a></li>
                        </ul>
                    </li>
                    <li><a asp-controller="" asp-action=""><strong>Refferal Listing</strong></a></li>
                </ul>
            </li>
        }
        @if (IsGranted("Pages.Scholarships"))
        {
            <li id="Scholarships">
                <span><strong>Scholarships</strong></span>
                <ul>
                    <li><a asp-controller="Scholarship" asp-action="Register"><strong>Scholarship Registration</strong></a></li>
                    @if (IsGranted("Pages.Scholarships"))
                    {
                        <li><a asp-controller="Scholarship" asp-action="List"><strong>Scholarship List</strong></a></li>
                    }
                </ul>
            </li>
        }
        @if (IsGranted("Pages.FileManager"))
        {
            <li><a asp-controller="" asp-action=""><strong>File Manager</strong></a></li>
        }
        @if (IsGranted("Pages.ExpenseManager"))
        {
            <li><a asp-controller="" asp-action=""><strong>Expense Manager</strong></a></li>
        }
        @if (IsGranted("Pages.AdminUses"))
        {
            <li id="Admins">
                <span><strong>Admin</strong></span>
                <ul>
                    <li><a asp-controller="Users" asp-action="Index"><strong>User Listing</strong></a></li>
                    <li><a asp-controller="Roles" asp-action="Index"><strong>Role Listing</strong></a></li>
                </ul>
            </li>
        }
            @*<li></li>
            <li><a asp-controller="" asp-action=""><strong>Members</strong></a></li>
            <li><a asp-controller="Partners" asp-action="Index"><strong>Partners</strong></a></li>
            <li>
                <span><strong>Teams</strong></span>
                <ul>
                    <li><a asp-controller="Teams" asp-action="Index"><strong>TLP Teams</strong></a></li>
                    <li><a asp-controller="" asp-action=""><strong>Coaching</strong></a></li>
                    <li><a asp-controller="" asp-action=""><strong>Consulting</strong></a></li>
                </ul>
            </li>
            <li><a asp-controller="" asp-action=""><strong>Meetings</strong></a></li>
            <li><a asp-controller="" asp-action=""><strong>Dashboard</strong></a></li>
            <li>
                <span><strong>Reports</strong></span>
                <ul>
                    <li><a asp-controller="" asp-action=""><strong>Payment Summary</strong></a></li>
                    <li><a asp-controller="" asp-action=""><strong>Member Payment Logs</strong></a></li>
                </ul>
            </li>
            <li>
                <span><strong>Referrals</strong></span>
                <ul>
                    <li>
                        <span><strong>Referral Registration</strong></span>
                        <ul>
                            <li><a asp-controller="" asp-action=""><strong>Partner Referral</strong></a></li>
                            <li><a asp-controller="" asp-action=""><strong>TLP Teams Referral</strong></a></li>
                            <li><a asp-controller="" asp-action=""><strong>Coaching Referral</strong></a></li>
                            <li><a asp-controller="" asp-action=""><strong>Consulting Referral</strong></a></li>
                            <li><a asp-controller="" asp-action=""><strong>Essential Work</strong></a></li>
                        </ul>
                    </li>
                    <li><a asp-controller="" asp-action=""><strong>Refferal Listing</strong></a></li>
                </ul>
            </li>
            <li>
                <span><strong>Scholarships</strong></span>
                <ul>
                    <li><a asp-controller="" asp-action=""><strong>Scholarship Registration</strong></a></li>
                    <li><a asp-controller="" asp-action=""><strong>Scholarship List</strong></a></li>
                </ul>
            </li>
            <li><a asp-controller="" asp-action=""><strong>File Manager</strong></a></li>
            <li><a asp-controller="" asp-action=""><strong>Expense Manager</strong></a></li>
            <li>
                <span><strong>Admin</strong></span>
                <ul>
                    <li><a asp-controller="" asp-action=""><strong>User Listing</strong></a></li>
                </ul>
            </li>*@
        </ul>
</nav>


@*@inject TownSend.Web.Views.Shared.Components.Navigation.HubOneNavigation navMenu

    <nav id="my-menu">
        <ul>
            <li></li>

            @foreach (var navItem in navMenu.NavMenuList)
            {
                if (navItem.childNavigation == null || navItem.childNavigation.Count == 0)
                {
                    <li><a href="@navItem.PageLink"><strong>@navItem.NavName</strong></a></li>
                }
                else
                {
                    <li id="@navItem.Id">
                        <span><strong>@navItem.NavName</strong></span>
                        <ul>
                            @foreach (var childNavItem in navItem.childNavigation)
                            {
                                if (childNavItem.childNavigation == null || childNavItem.childNavigation.Count == 0)
                                {
                                    <li><a href="@childNavItem.PageLink"><strong>@childNavItem.NavName</strong></a></li>
                                }
                                else
                                {
                                    <li>
                                        <span><strong>@childNavItem.NavName</strong></span>
                                        <ul>
                                            @foreach (var childChildNavItem in childNavItem.childNavigation)
                                            {
                                                <li><a href="@childChildNavItem.PageLink"><strong>@childChildNavItem.NavName</strong></a></li>
                                            }
                                        </ul>
                                    </li>
                                }

                            }
                        </ul>
                    </li>
                }
            }
        </ul>
    </nav>*@